=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.5.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EsiRuby::GetAlliancesAllianceIdOk
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetAlliancesAllianceIdOk' do
  before do
    # run before each test
    @instance = EsiRuby::GetAlliancesAllianceIdOk.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetAlliancesAllianceIdOk' do
    it 'should create an instact of GetAlliancesAllianceIdOk' do
      expect(@instance).to be_instance_of(EsiRuby::GetAlliancesAllianceIdOk)
    end
  end
  describe 'test attribute "alliance_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "date_founded"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "executor_corp"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ticker"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

