=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.5.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EsiRuby::GetUniverseSystemsSystemIdPlanet
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetUniverseSystemsSystemIdPlanet' do
  before do
    # run before each test
    @instance = EsiRuby::GetUniverseSystemsSystemIdPlanet.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetUniverseSystemsSystemIdPlanet' do
    it 'should create an instact of GetUniverseSystemsSystemIdPlanet' do
      expect(@instance).to be_instance_of(EsiRuby::GetUniverseSystemsSystemIdPlanet)
    end
  end
  describe 'test attribute "moons"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "planet_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

