=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.5.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for EsiRuby::GetInsurancePrices200Ok
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetInsurancePrices200Ok' do
  before do
    # run before each test
    @instance = EsiRuby::GetInsurancePrices200Ok.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetInsurancePrices200Ok' do
    it 'should create an instact of GetInsurancePrices200Ok' do
      expect(@instance).to be_instance_of(EsiRuby::GetInsurancePrices200Ok)
    end
  end
  describe 'test attribute "levels"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "type_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

